<!DOCTYPE html>
<!--
TODO - Add bootstrap and javascript files.
-->
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <meta charset="UTF-8">
        <title>Authorize</title>
    </head>
    <body id="body">
        <div class='panel panel-default'>
            <div class='panel-heading'>
                <?php echo $request->getClient()->getName(); ?> wants access to the following information:
            </div>
            <ul class='list-group'>
                <?php foreach($request->getScope() as $scope) { ?>
                    <li class='list-group-item'>
                        <div class='input-group'>
                            <span class='input-group-addon'>
                                <input type="checkbox" data-key="<?php echo strtolower($scope); ?>"
                                 data-checked="1" checked="checked" class="permission"/>
                            </span>
                            <input type="text" disabled class='form-control' value='<?php echo \Models\BaseModel::parsePermission($scope); ?>'/>
                        </div>
                    </li>
                <?php } ?>
            </ul>
            <div class='panel-footer'>
                <button class="button btn btn-primary" data-auth="accept">Accept</button>
                <button class="button btn btn-default" data-auth="decline">Decline</button>
            </div>
        </div>
        <style>body { padding:20px;}.panel { width:50%;} .form-control[disabled]{cursor:default;}.panel-footer{border-top:none;}</style>
        <script type="text/javascript" src="/js/authorize.js"></script>
        <script type="text/javascript">
            init('<?php echo $request->getRequestID(); ?>', '<?php echo $userID; ?>');
        </script>
    </body>
</html>
