<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
        <meta charset="UTF-8">
        <title></title>
    </head>
    <body id="body">
        <p><?php $this->flashSession->output(); ?></p>
        <div class='panel panel-default'>
            <div class='panel-heading'>
                Please Login to your account.
            </div>
            <div class='panel-body'>
                <input  class='form-control' data-placement='right' title='Email Address'
                        data-content='Please input a valid email address, For example "someone@ahost.com".'
                        type="email" placeholder="Email" id="email" required/>
                <input type="password" data-placement='bottom' title='Password' class='form-control'
                       placeholder="Password" id="pass" data-content='Please input a password. A password needs to be at least 6 characters and can 
                       only contain A-Z, 0-9, a-z, _ or -' required/>
            </div>
            <div class='panel-footer'>
                <button id="submit" class="btn btn-primary">Submit</button>
            </div>
        </div>
        <style>.panel input { margin-top:10px;}body { padding:20px;}.panel { width:50%;}</style>
        <script type="text/javascript" src='/js/login.js'></script>
        <script type="text/javascript">init('<?php echo $request->getRequestID(); ?>');</script>
    </body>
</html>
