<!DOCTYPE html>

<html>
    <head>
        <title>Example Application</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php echo $this->flashSession->output(); ?>
        <div style='padding:25px;'>
        <div class="panel panel-default">
            <div class="panel-heading">
                Profile Found.
            </div>
            <div class="panel-body">
                <ul class='list-group'>
                    <li class='list-group-item'>UserID: <?php echo $data['userID']; ?></li>
                    <li class='list-group-item'>Email: <?php echo $data['emailAddress']; ?></li>
                    <li class='list-group-item'>Name: <?php echo $data['name']; ?></li>
                </ul>
            </div>
        </div>
        </div>
    </body>
</html>