<!DOCTYPE html>

<html>
    <head>
        <title>Example Application</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
        <script type="text/javascript" src="/js/jquery-1.11.0.min.js"></script>
        <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
    <body>
        <?php echo \Phalcon\Tag::form(array('', 'method' => 'POST')) ?>
        <div class="panel panel-default">
            <div class="panel-footer">
                <?php echo \Phalcon\Tag::submitButton(array('submit', 'class' => 'btn btn-primary', 'value' => 'Login With Service')); ?>
            </div>
        </div>
        <?php echo \Phalcon\Tag::endForm(); ?>
    </body>
</html>
